/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLlmRouteImport } from './routes/api/llm'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'

const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmRoute = ApiLlmRouteImport.update({
  id: '/api/llm',
  path: '/api/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favicon.ico' | '/api/catalog' | '/api/llm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favicon.ico' | '/api/catalog' | '/api/llm'
  id: '__root__' | '/' | '/favicon.ico' | '/api/catalog' | '/api/llm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiLlmRoute: typeof ApiLlmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm': {
      id: '/api/llm'
      path: '/api/llm'
      fullPath: '/api/llm'
      preLoaderRoute: typeof ApiLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiLlmRoute: ApiLlmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
